/*
 * CommunicationstatesSuite.java
 * JUnit based test
 *
 * Created on May 23, 2008, 10:22 AM
 */

package adhoc.nodes.communicationstates;

import junit.framework.*;

/**
 *
 * @author paul
 */
public class CommunicationstatesSuite extends TestCase {
    
    public CommunicationstatesSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("CommunicationstatesSuite");
        suite.addTest(adhoc.nodes.communicationstates.InvitorTest.suite());
        suite.addTest(adhoc.nodes.communicationstates.InviteeTest.suite());
        suite.addTest(adhoc.nodes.communicationstates.IdleTest.suite());
        return suite;
    }
    
}
