/*
 * AlesLarryUI.java
 *
 * Created on November 17, 2005, 5:47 PM
 */

package ales;

import ales.creature.Creature;
import ales.structure.CreatureStore;
import javax.swing.*;
import java.awt.*;
import structure.*;

/**
 *
 * @author  leisenstein
 */
public class AlesLarryUI extends javax.swing.JFrame {
    
    private ALES_Game ales;
    private CreatureStore cs;
    /** Creates new form AlesLarryUI */
    public AlesLarryUI( ALES_Game a ) {
        super("ALES");//like ALES_UI.old
        ales = a;
        initComponents();
        
    }

    //Larry's code
    public javax.swing.JPanel getDrawPanel() {
		return jPanel_DrawScreen;
	}
       
    public javax.swing.JLabel getDrawLabel()
    {
                return jLabel1;
    }
    ////////////////////////////////////////////////////////////////////////////////////
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel_Sliders = new javax.swing.JPanel();
        jSlider_Oxygen = new javax.swing.JSlider();
        jSlider_Nutrients = new javax.swing.JSlider();
        jSlider_Alkalinity = new javax.swing.JSlider();
        jPB_Oxygen = new javax.swing.JProgressBar();
        jPB_Nutrients = new javax.swing.JProgressBar();
        jPB_Alkalinity = new javax.swing.JProgressBar();
        jLabel_Alkalinity = new javax.swing.JLabel();
        jLabel_Nutrients = new javax.swing.JLabel();
        jLabel_Oxygen = new javax.swing.JLabel();
        jPanel_DrawScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_VCRButtons = new javax.swing.JPanel();
        jLabel_Play = new javax.swing.JLabel();
        jLabel_Pause = new javax.swing.JLabel();
        jLabel_Fast = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_New = new javax.swing.JMenuItem();
        jMenuItem_Load = new javax.swing.JMenuItem();
        jMenuItem_Save = new javax.swing.JMenuItem();
        jMenuItem_SaveAs = new javax.swing.JMenuItem();
        jMenuItem_Exit = new javax.swing.JMenuItem();
        jMenu_ALES = new javax.swing.JMenu();
        jMenuItem_AddPlant = new javax.swing.JMenuItem();
        jMenuItem_AddHerbivore = new javax.swing.JMenuItem();
        jMenuItem_Carnivore = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem_DestroyAll = new javax.swing.JMenuItem();
        jCheckBox_Grid = new javax.swing.JCheckBoxMenuItem();
        jMenu_Help = new javax.swing.JMenu();
        jMenuItem_Contents = new javax.swing.JMenuItem();
        jMenuItem_About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A.L.E.S. Simulation");
        setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Sliders.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSlider_Oxygen.setMajorTickSpacing(10000);
        jSlider_Oxygen.setMaximum(100000);
        jSlider_Oxygen.setMinorTickSpacing(1000);
        jSlider_Oxygen.setValue(50000);
        jSlider_Oxygen.setValueIsAdjusting(true);
        jSlider_Oxygen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_OxygenStateChanged(evt);
            }
        });
        jSlider_Oxygen.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jSlider_OxygenCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jSlider_Nutrients.setMajorTickSpacing(10000);
        jSlider_Nutrients.setMaximum(100000);
        jSlider_Nutrients.setMinorTickSpacing(1000);
        jSlider_Nutrients.setValue(50000);
        jSlider_Nutrients.setValueIsAdjusting(true);
        jSlider_Nutrients.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_NutrientsStateChanged(evt);
            }
        });

        jSlider_Alkalinity.setMajorTickSpacing(10000);
        jSlider_Alkalinity.setMaximum(100000);
        jSlider_Alkalinity.setMinorTickSpacing(1000);
        jSlider_Alkalinity.setValue(50000);
        jSlider_Alkalinity.setValueIsAdjusting(true);
        jSlider_Alkalinity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_AlkalinityStateChanged(evt);
            }
        });

        jPB_Oxygen.setBackground(new java.awt.Color(255, 255, 255));
        jPB_Oxygen.setForeground(new java.awt.Color(0, 0, 255));
        jPB_Oxygen.setMaximum(100000);

        jPB_Nutrients.setBackground(new java.awt.Color(255, 255, 255));
        jPB_Nutrients.setForeground(new java.awt.Color(204, 0, 0));
        jPB_Nutrients.setMaximum(100000);

        jPB_Alkalinity.setBackground(new java.awt.Color(255, 255, 255));
        jPB_Alkalinity.setForeground(new java.awt.Color(0, 153, 0));
        jPB_Alkalinity.setMaximum(100000);

        jLabel_Alkalinity.setText("Alkalinity");

        jLabel_Nutrients.setText("Nutrients");

        jLabel_Oxygen.setText("Oxygen");

        org.jdesktop.layout.GroupLayout jPanel_SlidersLayout = new org.jdesktop.layout.GroupLayout(jPanel_Sliders);
        jPanel_Sliders.setLayout(jPanel_SlidersLayout);
        jPanel_SlidersLayout.setHorizontalGroup(
            jPanel_SlidersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_SlidersLayout.createSequentialGroup()
                .add(jPanel_SlidersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_SlidersLayout.createSequentialGroup()
                        .add(59, 59, 59)
                        .add(jPanel_SlidersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jSlider_Oxygen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPB_Oxygen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_SlidersLayout.createSequentialGroup()
                        .add(95, 95, 95)
                        .add(jLabel_Oxygen)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 64, Short.MAX_VALUE)
                .add(jPanel_SlidersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSlider_Nutrients, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPB_Nutrients, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_SlidersLayout.createSequentialGroup()
                        .add(36, 36, 36)
                        .add(jLabel_Nutrients)))
                .add(68, 68, 68)
                .add(jPanel_SlidersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSlider_Alkalinity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPB_Alkalinity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_SlidersLayout.createSequentialGroup()
                        .add(34, 34, 34)
                        .add(jLabel_Alkalinity)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel_SlidersLayout.setVerticalGroup(
            jPanel_SlidersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_SlidersLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel_SlidersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_SlidersLayout.createSequentialGroup()
                        .add(jLabel_Oxygen)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSlider_Oxygen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPB_Oxygen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_SlidersLayout.createSequentialGroup()
                        .add(jLabel_Alkalinity)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSlider_Alkalinity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPB_Alkalinity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_SlidersLayout.createSequentialGroup()
                        .add(jLabel_Nutrients)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSlider_Nutrients, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPB_Nutrients, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel_DrawScreen.setBackground(new java.awt.Color(153, 153, 255));
        jPanel_DrawScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_DrawScreen.setAlignmentX(0.0F);
        jPanel_DrawScreen.setAlignmentY(0.0F);
        jPanel_DrawScreen.setAutoscrolls(true);
        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ales\\images\\backgroundgrid.gif"));
        jLabel1.setDoubleBuffered(true);
        jLabel1.setMaximumSize(new java.awt.Dimension(640, 480));
        jLabel1.setMinimumSize(new java.awt.Dimension(640, 480));
        jLabel1.setPreferredSize(new java.awt.Dimension(640, 480));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel_DrawScreenLayout = new org.jdesktop.layout.GroupLayout(jPanel_DrawScreen);
        jPanel_DrawScreen.setLayout(jPanel_DrawScreenLayout);
        jPanel_DrawScreenLayout.setHorizontalGroup(
            jPanel_DrawScreenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_DrawScreenLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 597, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_DrawScreenLayout.setVerticalGroup(
            jPanel_DrawScreenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel_DrawScreenLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 404, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel_Play.setIcon(new javax.swing.ImageIcon("C:\\ales\\images\\vcrplay_small.gif"));
        jLabel_Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PlayMouseClicked(evt);
            }
        });

        jLabel_Pause.setIcon(new javax.swing.ImageIcon("C:\\ales\\images\\vcrpause_small.gif"));
        jLabel_Pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PauseMouseClicked(evt);
            }
        });

        jLabel_Fast.setIcon(new javax.swing.ImageIcon("C:\\ales\\images\\vcrfastforward_small.gif"));
        jLabel_Fast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_FastMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel_VCRButtonsLayout = new org.jdesktop.layout.GroupLayout(jPanel_VCRButtons);
        jPanel_VCRButtons.setLayout(jPanel_VCRButtonsLayout);
        jPanel_VCRButtonsLayout.setHorizontalGroup(
            jPanel_VCRButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_VCRButtonsLayout.createSequentialGroup()
                .add(259, 259, 259)
                .add(jLabel_Play)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel_Pause)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel_Fast)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel_VCRButtonsLayout.setVerticalGroup(
            jPanel_VCRButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_VCRButtonsLayout.createSequentialGroup()
                .add(jPanel_VCRButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.BASELINE, jLabel_Pause)
                    .add(org.jdesktop.layout.GroupLayout.BASELINE, jLabel_Play)
                    .add(org.jdesktop.layout.GroupLayout.BASELINE, jLabel_Fast))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu_File.setText("File");
        jMenu_File.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_FileMouseClicked(evt);
            }
        });

        jMenuItem_New.setText("New");
        jMenuItem_New.setEnabled(false);
        jMenu_File.add(jMenuItem_New);

        jMenuItem_Load.setText("Load Game");
        jMenuItem_Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LoadActionPerformed(evt);
            }
        });
        jMenuItem_Load.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem_LoadMouseClicked(evt);
            }
        });

        jMenu_File.add(jMenuItem_Load);

        jMenuItem_Save.setText("Save");
        jMenuItem_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SaveActionPerformed(evt);
            }
        });
        jMenuItem_Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem_SaveMouseClicked(evt);
            }
        });

        jMenu_File.add(jMenuItem_Save);

        jMenuItem_SaveAs.setText("Save As...");
        jMenuItem_SaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SaveAsActionPerformed(evt);
            }
        });
        jMenuItem_SaveAs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem_SaveAsMouseClicked(evt);
            }
        });

        jMenu_File.add(jMenuItem_SaveAs);

        jMenuItem_Exit.setText("Exit");
        jMenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ExitActionPerformed(evt);
            }
        });

        jMenu_File.add(jMenuItem_Exit);

        jMenuBar1.add(jMenu_File);

        jMenu_ALES.setText("A.L.E.S.");
        jMenu_ALES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_ALESMouseClicked(evt);
            }
        });

        jMenuItem_AddPlant.setText("Add Plant");
        jMenuItem_AddPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AddPlantActionPerformed(evt);
            }
        });

        jMenu_ALES.add(jMenuItem_AddPlant);

        jMenuItem_AddHerbivore.setText("Add Herbivore");
        jMenuItem_AddHerbivore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AddHerbivoreActionPerformed(evt);
            }
        });

        jMenu_ALES.add(jMenuItem_AddHerbivore);

        jMenuItem_Carnivore.setText("Add Carnivore");
        jMenuItem_Carnivore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CarnivoreActionPerformed(evt);
            }
        });

        jMenu_ALES.add(jMenuItem_Carnivore);

        jMenu_ALES.add(jSeparator1);

        jMenuItem_DestroyAll.setText("Genocide (Destroy All)");
        jMenuItem_DestroyAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_DestroyAllActionPerformed(evt);
            }
        });

        jMenu_ALES.add(jMenuItem_DestroyAll);

        jCheckBox_Grid.setSelected(true);
        jCheckBox_Grid.setText("Show Grid");
        jCheckBox_Grid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox_GridItemStateChanged(evt);
            }
        });

        jMenu_ALES.add(jCheckBox_Grid);

        jMenuBar1.add(jMenu_ALES);

        jMenu_Help.setText("Help");
        jMenu_Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_HelpMouseClicked(evt);
            }
        });

        jMenuItem_Contents.setText("Contents");
        jMenu_Help.add(jMenuItem_Contents);

        jMenuItem_About.setText("About A.L.E.S.");
        jMenuItem_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AboutActionPerformed(evt);
            }
        });

        jMenu_Help.add(jMenuItem_About);

        jMenuBar1.add(jMenu_Help);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_Sliders)
                        .add(jPanel_DrawScreen))
                    .add(jPanel_VCRButtons))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel_Sliders, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel_DrawScreen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(jPanel_VCRButtons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jMenuItem_SaveAsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_SaveAsMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_SaveAsMouseClicked

    private void jMenuItem_SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_SaveMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_SaveMouseClicked

    private void jMenuItem_LoadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_LoadMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_LoadMouseClicked

    private void jMenu_HelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_HelpMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu_HelpMouseClicked

    private void jMenu_ALESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_ALESMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu_ALESMouseClicked

    private void jMenu_FileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_FileMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu_FileMouseClicked

    private void jLabel_FastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_FastMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel_FastMouseClicked


    
    private void jLabel_PauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PauseMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel_PauseMouseClicked

    private void jLabel_PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PlayMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel_PlayMouseClicked

    private void jMenuItem_CarnivoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CarnivoreActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_CarnivoreActionPerformed

    private void jMenuItem_AddHerbivoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AddHerbivoreActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_AddHerbivoreActionPerformed

    private void jMenuItem_AddPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AddPlantActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_AddPlantActionPerformed

    private void jMenuItem_LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LoadActionPerformed
        JFileChooser jFileChooser = new JFileChooser();       
        int option;
        java.io.File file;
        String filename;
       option = jFileChooser.showSaveDialog(null);
       if( option == JFileChooser.APPROVE_OPTION )
       {
           file = jFileChooser.getSelectedFile();
           filename = file.toString();
           LoadGameStore.loadGame(ales.cs,filename);
           System.out.println(filename);
       }
    }//GEN-LAST:event_jMenuItem_LoadActionPerformed

    private void jCheckBox_GridItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox_GridItemStateChanged
        if(evt.getStateChange() == evt.SELECTED)
            ales.anim.grid = true;
        else
            ales.anim.grid = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_GridItemStateChanged

    public void setPB_Oxygen(int value)
    {
        jPB_Oxygen.setValue(value);
    }
    
    public void setPB_Nutrients(int value)
    {
        jPB_Nutrients.setValue(value);
    }
    public void setPB_Alkalinity(int value)
    {
        jPB_Alkalinity.setValue(value);
    }
    
    public int getOxygen()
    {
        return ((int)jSlider_Oxygen.getValue());
    }
    public int getNutrients()
    {
        return ((int)jSlider_Nutrients.getValue());
     }
    
    public int getAlkalinity()
    {
        return ((int)jSlider_Alkalinity.getValue());
    }

    public void setOxygen(int o1)
    {
        jSlider_Oxygen.setValue(o1);
    }
    public void setNutrients(int n1)
    {
        jSlider_Nutrients.setValue(n1);
     }
    
    public void setAlkalinity(int a1)
    {
        jSlider_Alkalinity.setValue(a1);
    }
    
    /**
     * test stub
     */
    private void redrawGrid()
    { // this will clear the entire screen
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ales\\images\\backgroundgrid.gif"));
    }

    /**
     * test stub
     */
    private void redrawNoGrid()
    { // this will clear the entire screen
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ales\\images\\background.gif"));
    }
    
    /**
     * test stub
     */
    private void testDraw()
    {// just try drawing a creature onto the existing background
        
        Graphics graph = jLabel1.getGraphics();
        ImageIcon image2 = new ImageIcon("c:\\images\\algaeadult.gif");
        graph.drawImage(image2.getImage(),0,0,null);
        graph.drawImage(image2.getImage(),33,32,null);
        //graph.drawImage(image2.getImage(),20,36,null);
    }
    
    private void jMenuItem_DestroyAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_DestroyAllActionPerformed
        
        Creature c;
        CreatureStore cs = ales.cs.getAll();
        while ( cs.hasNext()) {
            c = (ales.creature.Creature) cs.getNextVertex();
            c.consumed();
        }
    }//GEN-LAST:event_jMenuItem_DestroyAllActionPerformed

    public Point getHexDrawCoordinate(int x1, int y1)
    {
        x1 = (x1 - (x1 % 16)) + 4; // this finds the upper left corner of the hex, then adds 4 to it
        y1 = (y1 - (y1 % 16)) + 4; // this finds the upper left corner of the hex, then adds 4 to it
        Point mypoint = new Point(x1,y1);  // initialized to (x1,y1)
     
        return mypoint;
    }
    public Point getHexDrawCoordinate(Point p1)
    {
        int x1 = 0;
        int y1 = 0;
        x1 = (x1 - (x1 % 16)) + 3; // this finds the upper left corner of the hex, then adds 3 to it
        y1 = (y1 - (y1 % 16)) + 3; // this finds the upper left corner of the hex, then adds 3 to it
        
        p1.setLocation(x1,y1);
        return p1;
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
// This is the image label for the background
        int mouseX, mouseY;
        mouseX = evt.getX();
        mouseY = evt.getY();
        
        System.out.print("x= ");
        System.out.print(mouseX);
        System.out.print("   y= ");
        System.out.println(mouseY);
        
        //these coordinates will draw in the hex with an offset of +4 on the x & y points
        // Its only +3 b/c of the 0 start point
        // These calculations are based on a hex with 16pix diameter and a 12x12 image
        // This is not exact, but can be modified easily if needed.
        System.out.print("xDraw= ");
        System.out.print((int)getHexDrawCoordinate(mouseX,mouseY).getX());
        System.out.print("  yDraw = ");
        System.out.println((int)getHexDrawCoordinate(mouseX,mouseY).getY());


// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jSlider_AlkalinityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_AlkalinityStateChanged
// TODO add your handling code here:
        if(!jSlider_Alkalinity.getValueIsAdjusting())
        {
            System.out.print("Alkalinity = ");
            System.out.println(getAlkalinity());
            ales.board.setPh(getAlkalinity());
        }
    }//GEN-LAST:event_jSlider_AlkalinityStateChanged

    private void jSlider_NutrientsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_NutrientsStateChanged
// TODO add your handling code here:
        if(!jSlider_Nutrients.getValueIsAdjusting())
        {    
            System.out.print("Nutrients = ");
            System.out.println(getNutrients());
            ales.board.setNutrient(getNutrients());
        }
    }//GEN-LAST:event_jSlider_NutrientsStateChanged

    private void jSlider_OxygenCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jSlider_OxygenCaretPositionChanged
// TODO add your handling code here:
    }//GEN-LAST:event_jSlider_OxygenCaretPositionChanged

    private void jSlider_OxygenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_OxygenStateChanged
// This is if the slider is changed
        if(!jSlider_Oxygen.getValueIsAdjusting())
        {   System.out.print("Oxygen = ");
            System.out.println(getOxygen());
            ales.board.setOxygen(getOxygen());
        }
    }//GEN-LAST:event_jSlider_OxygenStateChanged

    
    public void myinit()
    {
        
        
    }
    private void jMenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_ExitActionPerformed

    private void jMenuItem_SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SaveAsActionPerformed
// TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();       
        int option;
        java.io.File file;
        String filename;
       option = jFileChooser.showSaveDialog(null);
       if( option == JFileChooser.APPROVE_OPTION )
       {
           file = jFileChooser.getSelectedFile();
           filename = file.toString();
           LoadGameStore.saveGame(ales.cs.getAll(),filename);
           System.out.println(filename);
       }
    }//GEN-LAST:event_jMenuItem_SaveAsActionPerformed

    private void jMenuItem_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SaveActionPerformed
// TODO add your handling code here:
        String filename="default.dat";
        LoadGameStore.saveGame(ales.cs.getAll(),filename);
        System.out.println(filename);
       
    }//GEN-LAST:event_jMenuItem_SaveActionPerformed

    private void chooseBGImage() {                                                 
// Changes Background Image
        JFileChooser jFileChooser = new JFileChooser();       
        int option;
        java.io.File file;
        String filename;
       option = jFileChooser.showSaveDialog(null);
       if( option == JFileChooser.APPROVE_OPTION )
       {
           file = jFileChooser.getSelectedFile();
           filename = file.toString();
           //ales.anim.changeBGImage(filename);
           System.out.println(filename);
       }
    }                                                

    
    private void jMenuItem_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AboutActionPerformed
// Help -> About Menu Item
        JOptionPane.showMessageDialog(this,"A.L.E.S. - Artificial Life Ecosystem Simulation\n\n"
                + "Larry Eisenstein, Michael Balaum, John Daigle, Ed Bullwinkel\n"
                + "CSC4350 - Software Engineering\n"
                + "Professor: Dr. Hu\n"
                + "December 1, 2005\n","About A.L.E.S.",JOptionPane.PLAIN_MESSAGE);

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_AboutActionPerformed
    
    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlesLarryUI().setVisible(true);
            }
        });
    }
 */   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBox_Grid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Alkalinity;
    private javax.swing.JLabel jLabel_Fast;
    private javax.swing.JLabel jLabel_Nutrients;
    private javax.swing.JLabel jLabel_Oxygen;
    private javax.swing.JLabel jLabel_Pause;
    private javax.swing.JLabel jLabel_Play;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_About;
    private javax.swing.JMenuItem jMenuItem_AddHerbivore;
    private javax.swing.JMenuItem jMenuItem_AddPlant;
    private javax.swing.JMenuItem jMenuItem_Carnivore;
    private javax.swing.JMenuItem jMenuItem_Contents;
    private javax.swing.JMenuItem jMenuItem_DestroyAll;
    private javax.swing.JMenuItem jMenuItem_Exit;
    private javax.swing.JMenuItem jMenuItem_Load;
    private javax.swing.JMenuItem jMenuItem_New;
    private javax.swing.JMenuItem jMenuItem_Save;
    private javax.swing.JMenuItem jMenuItem_SaveAs;
    private javax.swing.JMenu jMenu_ALES;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JMenu jMenu_Help;
    private javax.swing.JProgressBar jPB_Alkalinity;
    private javax.swing.JProgressBar jPB_Nutrients;
    private javax.swing.JProgressBar jPB_Oxygen;
    private javax.swing.JPanel jPanel_DrawScreen;
    private javax.swing.JPanel jPanel_Sliders;
    private javax.swing.JPanel jPanel_VCRButtons;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider_Alkalinity;
    private javax.swing.JSlider jSlider_Nutrients;
    private javax.swing.JSlider jSlider_Oxygen;
    // End of variables declaration//GEN-END:variables
    
}
