/*
 * OverheadstatesSuite.java
 * JUnit based test
 *
 * Created on May 23, 2008, 10:26 AM
 */

package adhoc.nodes.overheadstates;

import junit.framework.*;

/**
 *
 * @author paul
 */
public class OverheadstatesSuite extends TestCase {
    
    public OverheadstatesSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("OverheadstatesSuite");
        suite.addTest(adhoc.nodes.overheadstates.SatedTest.suite());
        suite.addTest(adhoc.nodes.overheadstates.HungryTest.suite());
        return suite;
    }
    
}
