/*
 * DriverSuite.java
 * JUnit based test
 *
 * Created on May 23, 2008, 10:25 AM
 */

package adhoc.driver;

import junit.framework.*;

/**
 *
 * @author paul
 */
public class DriverSuite extends TestCase {
    
    public DriverSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("DriverSuite");
        suite.addTest(adhoc.driver.DriverTest.suite());
        return suite;
    }
    
}
