/*
 * StructureSuite.java
 * JUnit based test
 *
 * Created on June 28, 2008, 10:59 PM
 */

package adhoc.structure;

import junit.framework.*;

/**
 *
 * @author paul
 */
public class StructureSuite extends TestCase {
    
    public StructureSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("StructureSuite");
        suite.addTest(adhoc.structure.CoverageTest.suite());
        suite.addTest(adhoc.structure.EtherTest.suite());
        return suite;
    }
    
}
